version: "3.8"

services:
  auth-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - kafka
      - rabbitmq

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - kafka
      - rabbitmq

  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
