version: "3.8"

services:
  auth-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      # MySQL
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=123456
      - DB_NAME=ecommerce
      # MongoDB
      - MONGO_URI=mongodb://mongodb:27017/ecommerce_mongo
    depends_on:
      - kafka
      - rabbitmq
      - mysql
      - mongodb

  category-service:
    build:
      context: ./category-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      # MySQL
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=123456
      - DB_NAME=ecommerce
      # MongoDB
      - MONGO_URI=mongodb://mongodb:27017/ecommerce_mongo
    depends_on:
      - kafka
      - rabbitmq
      - mysql
      - mongodb

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      # MySQL
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=123456
      - DB_NAME=ecommerce
      # MongoDB
      - MONGO_URI=mongodb://mongodb:27017/ecommerce_mongo
    depends_on:
      - kafka
      - rabbitmq
      - mysql
      - mongodb

  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"   # host 3307 → container 3306
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  mongo_data:
