version: "3.8"

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: appuser
      DB_PASSWORD: 123456
      DB_NAME: ecommerce
      JWT_SECRET: 94aa54c60f2ad8e1284eae3b392229296466fd7f8678ed1f705e41a6a6043dcec0358aa8060318fa540e9b11962ff9ae
      JWT_EXPIRES_IN: 1h
    depends_on:
      - mysql
      - kafka
      - rabbitmq

  category-service:
    build:
      context: ./category-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: appuser
      DB_PASSWORD: 123456
      DB_NAME: ecommerce
      JWT_SECRET: 94aa54c60f2ad8e1284eae3b392229296466fd7f8678ed1f705e41a6a6043dcec0358aa8060318fa540e9b11962ff9ae
      JWT_EXPIRES_IN: 1h
    depends_on:
      - mysql
      - kafka
      - rabbitmq

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: appuser
      DB_PASSWORD: 123456
      DB_NAME: ecommerce
      JWT_SECRET: 94aa54c60f2ad8e1284eae3b392229296466fd7f8678ed1f705e41a6a6043dcec0358aa8060318fa540e9b11962ff9ae
      JWT_EXPIRES_IN: 1h
    depends_on:
      - mysql
      - kafka
      - rabbitmq

  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: appuser
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpass"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  mysql_data:
